services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: petedavis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reading
    networks:
      - readnet
    volumes:
      - readvol:/var/lib/postgresql/data
      # - /home/pdavis/davis/repos/reading-list:/docker-entrypoint-initdb.d # update paths to have compose init a sql posrtgres db from .sql file

  app:
    build:
      context: .
      dockerfile: ./Containerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
    networks:
      - readnet

networks:
  readnet:
    driver: bridge

volumes:
  readvol:
    driver: local
