services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - readnet
    volumes:
      - readvol:/var/lib/postgresql/data
      # - ./:/docker-entrypoint-initdb.d:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${DBNAME} -U $${USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: ./Containerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
    networks:
      - readnet
    depends_on:
      db:
        condition: service_healthy

networks:
  readnet:
    driver: bridge

volumes:
  readvol:
    driver: local