services:
  db:
    image: postgres:16.8
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=petedavis
      - POSTGRES_PASSWORD=testing123
    networks:
      - readnet
    volumes:
      - readvol:/var/lib/postgresql/data
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8501:8501"
    networks:
      - readnet
      
networks:
  readnet:
    driver: bridge
    
volumes:
  readvol:

 
